---
name: CI
on: pull_request

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: 1.18

      - name: Install ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Test
        run: |
          export GOPATH=$(go env GOPATH)
          make unit
