---
name: CI
on: pull_request

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: 1.22

      - name: Install ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Test
        run: |
          export GOPATH=$(go env GOPATH)
          make unit
