---
name: CI
on: pull_request

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: 1.18

      - name: Install ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Test
        run: |
          export GOPATH=$(go env GOPATH)
          make unit
