---
name: CI
on: pull_request

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install ginkgo
        run: go install github.com/onsi/ginkgo/ginkgo@latest

      - name: Test
        run: |
          export GOPATH=$(go env GOPATH)
          make unit
