// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/alphagov/paas-elasticache-broker/providers"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/secretsmanager"
)

type FakeSecretsManager struct {
	CreateSecretWithContextStub        func(context.Context, *secretsmanager.CreateSecretInput, ...request.Option) (*secretsmanager.CreateSecretOutput, error)
	createSecretWithContextMutex       sync.RWMutex
	createSecretWithContextArgsForCall []struct {
		arg1 context.Context
		arg2 *secretsmanager.CreateSecretInput
		arg3 []request.Option
	}
	createSecretWithContextReturns struct {
		result1 *secretsmanager.CreateSecretOutput
		result2 error
	}
	createSecretWithContextReturnsOnCall map[int]struct {
		result1 *secretsmanager.CreateSecretOutput
		result2 error
	}
	DeleteSecretWithContextStub        func(context.Context, *secretsmanager.DeleteSecretInput, ...request.Option) (*secretsmanager.DeleteSecretOutput, error)
	deleteSecretWithContextMutex       sync.RWMutex
	deleteSecretWithContextArgsForCall []struct {
		arg1 context.Context
		arg2 *secretsmanager.DeleteSecretInput
		arg3 []request.Option
	}
	deleteSecretWithContextReturns struct {
		result1 *secretsmanager.DeleteSecretOutput
		result2 error
	}
	deleteSecretWithContextReturnsOnCall map[int]struct {
		result1 *secretsmanager.DeleteSecretOutput
		result2 error
	}
	GetSecretValueWithContextStub        func(context.Context, *secretsmanager.GetSecretValueInput, ...request.Option) (*secretsmanager.GetSecretValueOutput, error)
	getSecretValueWithContextMutex       sync.RWMutex
	getSecretValueWithContextArgsForCall []struct {
		arg1 context.Context
		arg2 *secretsmanager.GetSecretValueInput
		arg3 []request.Option
	}
	getSecretValueWithContextReturns struct {
		result1 *secretsmanager.GetSecretValueOutput
		result2 error
	}
	getSecretValueWithContextReturnsOnCall map[int]struct {
		result1 *secretsmanager.GetSecretValueOutput
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSecretsManager) CreateSecretWithContext(arg1 context.Context, arg2 *secretsmanager.CreateSecretInput, arg3 ...request.Option) (*secretsmanager.CreateSecretOutput, error) {
	fake.createSecretWithContextMutex.Lock()
	ret, specificReturn := fake.createSecretWithContextReturnsOnCall[len(fake.createSecretWithContextArgsForCall)]
	fake.createSecretWithContextArgsForCall = append(fake.createSecretWithContextArgsForCall, struct {
		arg1 context.Context
		arg2 *secretsmanager.CreateSecretInput
		arg3 []request.Option
	}{arg1, arg2, arg3})
	stub := fake.CreateSecretWithContextStub
	fakeReturns := fake.createSecretWithContextReturns
	fake.recordInvocation("CreateSecretWithContext", []interface{}{arg1, arg2, arg3})
	fake.createSecretWithContextMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSecretsManager) CreateSecretWithContextCallCount() int {
	fake.createSecretWithContextMutex.RLock()
	defer fake.createSecretWithContextMutex.RUnlock()
	return len(fake.createSecretWithContextArgsForCall)
}

func (fake *FakeSecretsManager) CreateSecretWithContextCalls(stub func(context.Context, *secretsmanager.CreateSecretInput, ...request.Option) (*secretsmanager.CreateSecretOutput, error)) {
	fake.createSecretWithContextMutex.Lock()
	defer fake.createSecretWithContextMutex.Unlock()
	fake.CreateSecretWithContextStub = stub
}

func (fake *FakeSecretsManager) CreateSecretWithContextArgsForCall(i int) (context.Context, *secretsmanager.CreateSecretInput, []request.Option) {
	fake.createSecretWithContextMutex.RLock()
	defer fake.createSecretWithContextMutex.RUnlock()
	argsForCall := fake.createSecretWithContextArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSecretsManager) CreateSecretWithContextReturns(result1 *secretsmanager.CreateSecretOutput, result2 error) {
	fake.createSecretWithContextMutex.Lock()
	defer fake.createSecretWithContextMutex.Unlock()
	fake.CreateSecretWithContextStub = nil
	fake.createSecretWithContextReturns = struct {
		result1 *secretsmanager.CreateSecretOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeSecretsManager) CreateSecretWithContextReturnsOnCall(i int, result1 *secretsmanager.CreateSecretOutput, result2 error) {
	fake.createSecretWithContextMutex.Lock()
	defer fake.createSecretWithContextMutex.Unlock()
	fake.CreateSecretWithContextStub = nil
	if fake.createSecretWithContextReturnsOnCall == nil {
		fake.createSecretWithContextReturnsOnCall = make(map[int]struct {
			result1 *secretsmanager.CreateSecretOutput
			result2 error
		})
	}
	fake.createSecretWithContextReturnsOnCall[i] = struct {
		result1 *secretsmanager.CreateSecretOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeSecretsManager) DeleteSecretWithContext(arg1 context.Context, arg2 *secretsmanager.DeleteSecretInput, arg3 ...request.Option) (*secretsmanager.DeleteSecretOutput, error) {
	fake.deleteSecretWithContextMutex.Lock()
	ret, specificReturn := fake.deleteSecretWithContextReturnsOnCall[len(fake.deleteSecretWithContextArgsForCall)]
	fake.deleteSecretWithContextArgsForCall = append(fake.deleteSecretWithContextArgsForCall, struct {
		arg1 context.Context
		arg2 *secretsmanager.DeleteSecretInput
		arg3 []request.Option
	}{arg1, arg2, arg3})
	stub := fake.DeleteSecretWithContextStub
	fakeReturns := fake.deleteSecretWithContextReturns
	fake.recordInvocation("DeleteSecretWithContext", []interface{}{arg1, arg2, arg3})
	fake.deleteSecretWithContextMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSecretsManager) DeleteSecretWithContextCallCount() int {
	fake.deleteSecretWithContextMutex.RLock()
	defer fake.deleteSecretWithContextMutex.RUnlock()
	return len(fake.deleteSecretWithContextArgsForCall)
}

func (fake *FakeSecretsManager) DeleteSecretWithContextCalls(stub func(context.Context, *secretsmanager.DeleteSecretInput, ...request.Option) (*secretsmanager.DeleteSecretOutput, error)) {
	fake.deleteSecretWithContextMutex.Lock()
	defer fake.deleteSecretWithContextMutex.Unlock()
	fake.DeleteSecretWithContextStub = stub
}

func (fake *FakeSecretsManager) DeleteSecretWithContextArgsForCall(i int) (context.Context, *secretsmanager.DeleteSecretInput, []request.Option) {
	fake.deleteSecretWithContextMutex.RLock()
	defer fake.deleteSecretWithContextMutex.RUnlock()
	argsForCall := fake.deleteSecretWithContextArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSecretsManager) DeleteSecretWithContextReturns(result1 *secretsmanager.DeleteSecretOutput, result2 error) {
	fake.deleteSecretWithContextMutex.Lock()
	defer fake.deleteSecretWithContextMutex.Unlock()
	fake.DeleteSecretWithContextStub = nil
	fake.deleteSecretWithContextReturns = struct {
		result1 *secretsmanager.DeleteSecretOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeSecretsManager) DeleteSecretWithContextReturnsOnCall(i int, result1 *secretsmanager.DeleteSecretOutput, result2 error) {
	fake.deleteSecretWithContextMutex.Lock()
	defer fake.deleteSecretWithContextMutex.Unlock()
	fake.DeleteSecretWithContextStub = nil
	if fake.deleteSecretWithContextReturnsOnCall == nil {
		fake.deleteSecretWithContextReturnsOnCall = make(map[int]struct {
			result1 *secretsmanager.DeleteSecretOutput
			result2 error
		})
	}
	fake.deleteSecretWithContextReturnsOnCall[i] = struct {
		result1 *secretsmanager.DeleteSecretOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeSecretsManager) GetSecretValueWithContext(arg1 context.Context, arg2 *secretsmanager.GetSecretValueInput, arg3 ...request.Option) (*secretsmanager.GetSecretValueOutput, error) {
	fake.getSecretValueWithContextMutex.Lock()
	ret, specificReturn := fake.getSecretValueWithContextReturnsOnCall[len(fake.getSecretValueWithContextArgsForCall)]
	fake.getSecretValueWithContextArgsForCall = append(fake.getSecretValueWithContextArgsForCall, struct {
		arg1 context.Context
		arg2 *secretsmanager.GetSecretValueInput
		arg3 []request.Option
	}{arg1, arg2, arg3})
	stub := fake.GetSecretValueWithContextStub
	fakeReturns := fake.getSecretValueWithContextReturns
	fake.recordInvocation("GetSecretValueWithContext", []interface{}{arg1, arg2, arg3})
	fake.getSecretValueWithContextMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSecretsManager) GetSecretValueWithContextCallCount() int {
	fake.getSecretValueWithContextMutex.RLock()
	defer fake.getSecretValueWithContextMutex.RUnlock()
	return len(fake.getSecretValueWithContextArgsForCall)
}

func (fake *FakeSecretsManager) GetSecretValueWithContextCalls(stub func(context.Context, *secretsmanager.GetSecretValueInput, ...request.Option) (*secretsmanager.GetSecretValueOutput, error)) {
	fake.getSecretValueWithContextMutex.Lock()
	defer fake.getSecretValueWithContextMutex.Unlock()
	fake.GetSecretValueWithContextStub = stub
}

func (fake *FakeSecretsManager) GetSecretValueWithContextArgsForCall(i int) (context.Context, *secretsmanager.GetSecretValueInput, []request.Option) {
	fake.getSecretValueWithContextMutex.RLock()
	defer fake.getSecretValueWithContextMutex.RUnlock()
	argsForCall := fake.getSecretValueWithContextArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSecretsManager) GetSecretValueWithContextReturns(result1 *secretsmanager.GetSecretValueOutput, result2 error) {
	fake.getSecretValueWithContextMutex.Lock()
	defer fake.getSecretValueWithContextMutex.Unlock()
	fake.GetSecretValueWithContextStub = nil
	fake.getSecretValueWithContextReturns = struct {
		result1 *secretsmanager.GetSecretValueOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeSecretsManager) GetSecretValueWithContextReturnsOnCall(i int, result1 *secretsmanager.GetSecretValueOutput, result2 error) {
	fake.getSecretValueWithContextMutex.Lock()
	defer fake.getSecretValueWithContextMutex.Unlock()
	fake.GetSecretValueWithContextStub = nil
	if fake.getSecretValueWithContextReturnsOnCall == nil {
		fake.getSecretValueWithContextReturnsOnCall = make(map[int]struct {
			result1 *secretsmanager.GetSecretValueOutput
			result2 error
		})
	}
	fake.getSecretValueWithContextReturnsOnCall[i] = struct {
		result1 *secretsmanager.GetSecretValueOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeSecretsManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createSecretWithContextMutex.RLock()
	defer fake.createSecretWithContextMutex.RUnlock()
	fake.deleteSecretWithContextMutex.RLock()
	defer fake.deleteSecretWithContextMutex.RUnlock()
	fake.getSecretValueWithContextMutex.RLock()
	defer fake.getSecretValueWithContextMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSecretsManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ providers.SecretsManager = new(FakeSecretsManager)
